version: "3.8"
services:
    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #         target: builder
    #     command: 'npm run start'
    #     ports:
    #         - '3000:3000'
    #     volumes:
    #         - .:/usr/app
    #     environment:
    #         MONGO_HOST: mongo
    #         MONGO_PORT: 27017
    #         MONGO_DBNAME: deliverymuch
    #     depends_on:
    #         - mongo
    #         - stock-service
    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        environment:
            MONGO_HOST: localhost
            MONGO_PORT: 27017
            MONGO_DBNAME: deliverymuch
        container_name: mongo
        volumes:
            - mongodata:/data/mongo
    rabbitmq:
        image: rabbitmq:3.8-management
        networks:
          - app-network
        ports:
          - 5672:5672
          - 15672:15672
    stock-service:
        image: deliverymuch/backend-challenge:stock-service
        networks:
          - app-network
        environment:
          - RABBITMQ_URL=amqp://rabbitmq
        depends_on:
          - rabbitmq
        links:
          - rabbitmq
        restart: on-failure
networks:
  app-network:
    driver: bridge
volumes:
    mongodata:
